VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 config.vm.box = "ansible_test_centos7_1"
    
 ## Linux上から共有するWindows上のフォルダを指定する
 config.vm.synced_folder "C:/dev", "/hostdev",
   mount_options: ['dmode=777', 'fmode=666']
    
 ## LinuxマシンのIPアドレスを指定する
 config.vm.network "private_network", ip: "192.168.56.102"
    
 ## vagrant初期起動時に走らせるシェルスクリプト用ファイルを指定する
 config.vm.provision :shell, :path => "provision.sh"
end